### ISSUE TITLE
todo - fresh mojave install

### ISSUE THREAD

**Issue by nonrational** [nonrational/dotfiles#1]
- [x] map capslock to ctrl
- [x] install mojave headers
- [x] tap to click
- [x] 3-finger page navigation
- [x] 4-finger space navigation
- [x] disable notifications (set do not disturb from 06:00 until 05:59)
- [x] invert function keys
- [x] export istat menus preference
- [ ] export divvy preferences
